# Generated by Django 5.2.11 on 2026-02-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subscriptionplan_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'En attente de paiement'), ('partial', 'Paiement partiel'), ('paid', 'Payé'), ('failed', 'Paiement échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20),
        ),
    ]
