# Generated by Django 5.1.6 on 2026-02-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_booking_payment_confirmed_at_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('mobile_money', 'Mobile Money'), ('payoneer', 'Payoneer'), ('cash_delivery', 'Paiement à la livraison'), ('credit_card', 'Carte de crédit'), ('fedapay', 'FedaPay')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('authorized', 'Autorisé'), ('pending_payment', 'En attente de paiement'), ('paid', 'Payé'), ('partial', 'Partiellement payé'), ('refunded', 'Remboursé'), ('failed', 'Échoué')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('mobile_money', 'Mobile Money'), ('payoneer', 'Payoneer'), ('cash_delivery', 'Paiement à la livraison'), ('credit_card', 'Carte de crédit'), ('fedapay', 'FedaPay')], max_length=20),
        ),
    ]
